#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialDesarrolloWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PARCIALDW")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCLIENTES(CLIENTES instance);
    partial void UpdateCLIENTES(CLIENTES instance);
    partial void DeleteCLIENTES(CLIENTES instance);
    partial void InsertUSUARIOS(USUARIOS instance);
    partial void UpdateUSUARIOS(USUARIOS instance);
    partial void DeleteUSUARIOS(USUARIOS instance);
    partial void InsertVENTAS(VENTAS instance);
    partial void UpdateVENTAS(VENTAS instance);
    partial void DeleteVENTAS(VENTAS instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLIENTES> CLIENTES
		{
			get
			{
				return this.GetTable<CLIENTES>();
			}
		}
		
		public System.Data.Linq.Table<USUARIOS> USUARIOS
		{
			get
			{
				return this.GetTable<USUARIOS>();
			}
		}
		
		public System.Data.Linq.Table<VENTAS> VENTAS
		{
			get
			{
				return this.GetTable<VENTAS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTES")]
	public partial class CLIENTES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _APELLIDO;
		
		private string _DIRECCION;
		
		private string _CORREO;
		
		private System.Nullable<decimal> _SALDO;
		
		private string _ESTADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnAPELLIDOChanging(string value);
    partial void OnAPELLIDOChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnCORREOChanging(string value);
    partial void OnCORREOChanged();
    partial void OnSALDOChanging(System.Nullable<decimal> value);
    partial void OnSALDOChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    #endregion
		
		public CLIENTES()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO", DbType="VarChar(100)")]
		public string APELLIDO
		{
			get
			{
				return this._APELLIDO;
			}
			set
			{
				if ((this._APELLIDO != value))
				{
					this.OnAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO = value;
					this.SendPropertyChanged("APELLIDO");
					this.OnAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(100)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(100)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this.OnCORREOChanging(value);
					this.SendPropertyChanging();
					this._CORREO = value;
					this.SendPropertyChanged("CORREO");
					this.OnCORREOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SALDO
		{
			get
			{
				return this._SALDO;
			}
			set
			{
				if ((this._SALDO != value))
				{
					this.OnSALDOChanging(value);
					this.SendPropertyChanging();
					this._SALDO = value;
					this.SendPropertyChanged("SALDO");
					this.OnSALDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(100)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIOS")]
	public partial class USUARIOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _APELLIDO;
		
		private string _CORREO;
		
		private string _CONTRASEÑA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnAPELLIDOChanging(string value);
    partial void OnAPELLIDOChanged();
    partial void OnCORREOChanging(string value);
    partial void OnCORREOChanged();
    partial void OnCONTRASEÑAChanging(string value);
    partial void OnCONTRASEÑAChanged();
    #endregion
		
		public USUARIOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO", DbType="VarChar(100)")]
		public string APELLIDO
		{
			get
			{
				return this._APELLIDO;
			}
			set
			{
				if ((this._APELLIDO != value))
				{
					this.OnAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO = value;
					this.SendPropertyChanged("APELLIDO");
					this.OnAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(100)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this.OnCORREOChanging(value);
					this.SendPropertyChanging();
					this._CORREO = value;
					this.SendPropertyChanged("CORREO");
					this.OnCORREOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRASEÑA", DbType="VarChar(100)")]
		public string CONTRASEÑA
		{
			get
			{
				return this._CONTRASEÑA;
			}
			set
			{
				if ((this._CONTRASEÑA != value))
				{
					this.OnCONTRASEÑAChanging(value);
					this.SendPropertyChanging();
					this._CONTRASEÑA = value;
					this.SendPropertyChanged("CONTRASEÑA");
					this.OnCONTRASEÑAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VENTAS")]
	public partial class VENTAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private System.Nullable<int> _CODIGO_CLIENTE;
		
		private string _FECHA;
		
		private string _SERIE_FACTURA;
		
		private System.Nullable<decimal> _NUMERO_FACTURA;
		
		private System.Nullable<decimal> _MONTO;
		
		private string _ESTADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnCODIGO_CLIENTEChanging(System.Nullable<int> value);
    partial void OnCODIGO_CLIENTEChanged();
    partial void OnFECHAChanging(string value);
    partial void OnFECHAChanged();
    partial void OnSERIE_FACTURAChanging(string value);
    partial void OnSERIE_FACTURAChanged();
    partial void OnNUMERO_FACTURAChanging(System.Nullable<decimal> value);
    partial void OnNUMERO_FACTURAChanged();
    partial void OnMONTOChanging(System.Nullable<decimal> value);
    partial void OnMONTOChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    #endregion
		
		public VENTAS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_CLIENTE", DbType="Int")]
		public System.Nullable<int> CODIGO_CLIENTE
		{
			get
			{
				return this._CODIGO_CLIENTE;
			}
			set
			{
				if ((this._CODIGO_CLIENTE != value))
				{
					this.OnCODIGO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_CLIENTE = value;
					this.SendPropertyChanged("CODIGO_CLIENTE");
					this.OnCODIGO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="VarChar(100)")]
		public string FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this.OnFECHAChanging(value);
					this.SendPropertyChanging();
					this._FECHA = value;
					this.SendPropertyChanged("FECHA");
					this.OnFECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIE_FACTURA", DbType="VarChar(100)")]
		public string SERIE_FACTURA
		{
			get
			{
				return this._SERIE_FACTURA;
			}
			set
			{
				if ((this._SERIE_FACTURA != value))
				{
					this.OnSERIE_FACTURAChanging(value);
					this.SendPropertyChanging();
					this._SERIE_FACTURA = value;
					this.SendPropertyChanged("SERIE_FACTURA");
					this.OnSERIE_FACTURAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_FACTURA", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> NUMERO_FACTURA
		{
			get
			{
				return this._NUMERO_FACTURA;
			}
			set
			{
				if ((this._NUMERO_FACTURA != value))
				{
					this.OnNUMERO_FACTURAChanging(value);
					this.SendPropertyChanging();
					this._NUMERO_FACTURA = value;
					this.SendPropertyChanged("NUMERO_FACTURA");
					this.OnNUMERO_FACTURAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> MONTO
		{
			get
			{
				return this._MONTO;
			}
			set
			{
				if ((this._MONTO != value))
				{
					this.OnMONTOChanging(value);
					this.SendPropertyChanging();
					this._MONTO = value;
					this.SendPropertyChanged("MONTO");
					this.OnMONTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(100)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
